In [1]:
import csv 
import torch
import torch.utils.data
import torch.nn.functional as F
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import argparse
from torch.optim import Adam
from torch.autograd import Variable
from RecurrentNet import RecurrentNet




filepath2 = "D:\\MLdata\\tracks.csv"
data2 = pd.read_csv(filepath2, index_col=0, header=[0,1])
y_col = data2.loc[:,( 'track', 'genre_top')].replace(to_replace=None, value=None, inplace=False, limit=None, regex=False, method='pad')
classes = set(y_col)
print(set(y_col))

{'Jazz', 'Country', 'Blues', 'Easy Listening', 'Electronic', 'Folk', 'Spoken', 'Hip-Hop', 'Old-Time / Historic', 'Classical', 'Pop', 'Soul-RnB', 'International', 'Rock', 'Experimental', 'Instrumental'}


In [2]:
import h5py
def read_hdf(file_path):
    return_dict = []
    with h5py.File(file_path, 'r') as hf:
        #print(list(hf.keys()))
        dataset = hf[file_path[9:-5]]
        #print(len(list(dataset.keys())))
        keys = list(dataset.keys())
        for i in keys:
            return_dict.append({
                "name":int(i.replace("-","/")[-10:-4]),
                "data":dataset[i][:]
            })
        return return_dict

In [3]:
from torch.optim import Adam
 
import argparse
import sys
import torch
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

class RecurrentNet(torch.nn.Module):
    def __init__(self, n_layers, seq_size, dropout, netType, n_inputs, n_outputs):
        super(LSTMNet, self).__init__()
        self.n_layers = n_layers
        self.seq_size = seq_size
        if netType == 'LSTM':
            self.rec = nn.LSTM(n_inputs, seq_size, n_layers, dropout = dropout)
        if newType == 'GRU':
            self.rec = nn.GRU(n_inputs, seq_size, n_layers, dropout = dropout)
        self.relu = nn.ReLU()
        self.hidden1 = nn.Linear(seq_size, seq_size)
        self.hidden2 = nn.Linear(seq_size, seq_size/2)
        self.output = nn.Linear(seq_size/2, n_outputs)
       
        
    def forward(self, x):
        out, _ = self.rec(x) 
        out = self.relu(self.hidden1(out))
        out = self.relu(self.hidden2(out))
        out = self.output(out) 
        return out
        


In [4]:
import random

x_data = []


#print(type(data))
n_outputs = 0
for k in classes:
    try:
        x_data.extend(read_hdf("D:/MLdata/" + k + ".hdf5"))
        print(len(x_data))
        n_outputs += 1
    except:
        pass
random.shuffle(x_data)
print(x_data[0]['name'])
print(x_data[2]['name'])
print(x_data[65]['name'])
print(x_data[17]['name'])
print(n_outputs)

999
1999
2999
3999
4999
5998
6997
7997
86799
55101
16745
110204
8


In [5]:
y_data = []
x_values = []
for i in x_data:
    y_data.append(y_col[i['name']])
    x_values.append(i['data'])
print(y_data[300])
print(x_values[300][-5:-1])
print(x_values[350][-5:-1])
print(x_values[10][-5:-1])
print(x_values[1000][-5:-1])


Instrumental
[[-66.70079  -80.       -80.       ... -80.       -80.       -68.532684]
 [-66.785904 -80.       -80.       ... -80.       -80.       -68.608505]
 [-66.847565 -80.       -80.       ... -80.       -80.       -68.6911  ]
 [-66.89369  -80.       -80.       ... -80.       -80.       -68.74369 ]]
[[-80. -80. -80. ... -80. -80. -80.]
 [-80. -80. -80. ... -80. -80. -80.]
 [-80. -80. -80. ... -80. -80. -80.]
 [-80. -80. -80. ... -80. -80. -80.]]
[[-80. -80. -80. ... -80. -80. -80.]
 [-80. -80. -80. ... -80. -80. -80.]
 [-80. -80. -80. ... -80. -80. -80.]
 [-80. -80. -80. ... -80. -80. -80.]]
[[-80. -80. -80. ... -80. -80. -80.]
 [-80. -80. -80. ... -80. -80. -80.]
 [-80. -80. -80. ... -80. -80. -80.]
 [-80. -80. -80. ... -80. -80. -80.]]


In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

label_encoder = LabelEncoder()
#x_col = x_data.to_numpy()
#print(len(y_col))
#print(len(x_col))
#print(len(x_col[0]))
#classes = set(y_col)
#print(len(classes))
y_data = label_encoder.fit_transform(np.ravel(y_data))
y_data = y_data.reshape(-1, 1)
print(y_data)
encoder = OneHotEncoder(drop='first', sparse=False)
# transform data
onehot_y = encoder.fit_transform(y_data)
print(onehot_y)
#print(y_data)
X_train, X_test, y_train, y_test = train_test_split(x_values , onehot_y,  test_size=0.2, random_state=42)
print(X_train[3])
print(y_train[3])

[[7]
 [6]
 [3]
 ...
 [0]
 [7]
 [5]]
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]]
[[-79.53497  -37.946716 -25.981203 ... -46.526627 -45.170944 -47.728416]
 [-78.38567  -28.388594 -24.553946 ... -38.197872 -44.150444 -48.61344 ]
 [-78.34117  -24.827425 -20.930473 ... -39.221027 -47.145493 -48.58551 ]
 ...
 [-80.       -80.       -80.       ... -80.       -80.       -80.      ]
 [-80.       -80.       -80.       ... -80.       -80.       -80.      ]
 [-80.       -80.       -80.       ... -80.       -80.       -80.      ]]
[1. 0. 0. 0. 0. 0. 0.]
